MYSQL_HISTORY_TABLE_SQL = """
CREATE TABLE IF NOT EXISTS photo_style_history (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    input_data JSON NOT NULL,
    output_data JSON NOT NULL,
    liked TINYINT(1) NOT NULL DEFAULT 0,
    shot_success TINYINT(1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
"""

MYSQL_USER_TABLE_SQL = """
CREATE TABLE IF NOT EXISTS photo_style_users (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(64) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    photo_path VARCHAR(500) NULL,
    photo_mime_type VARCHAR(100) NULL,
    face_analysis JSON NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
"""

SQLITE_HISTORY_TABLE_SQL = """
CREATE TABLE IF NOT EXISTS photo_style_history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    input_data TEXT NOT NULL,
    output_data TEXT NOT NULL,
    liked INTEGER NOT NULL DEFAULT 0,
    shot_success INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
"""

SQLITE_USER_TABLE_SQL = """
CREATE TABLE IF NOT EXISTS photo_style_users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    photo_path TEXT NULL,
    photo_mime_type TEXT NULL,
    face_analysis TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
"""
