#用户画像模块，默认召回语义锚点数量
DEFAULT_ANCHOR_TOP_K= 8

#qwen模型名称
QWEN_FACE_MODEL="qwen3.7-plus" # 人脸分析模型
QWEN_BASE_MODEL="qwen3-max" # 基础模型（建议生成，用户画像）
QWEN_SEMANTIC_ANCHOR_MODEL="qwen3.7-max" # 语义锚点生成模型


#语义轴取值
AXIS_VALUE_MIN=-1.0
AXIS_VALUE_MAX=1.0
AXIS_VALUE_DEFAULT=0.0
AXIS_VALUE_DECIMAL_PLACES=3

# 相似度取值
SIMILARITY_MIN = 0.0
SIMILARITY_MAX = 1.0
SEMANTIC_ANCHOR_SIMILARITY_THRESHOLD = 0.75
SEMANTIC_ANCHOR_MIN_COUNT = 1
